#include "config.hpp"

#include "util/cpuid.hpp"

namespace tblis
{

//TBLIS_CONFIG_INSTANTIATE(skx_32x6_l1);
//TBLIS_CONFIG_INSTANTIATE(skx_32x6_l2);
//TBLIS_CONFIG_INSTANTIATE(skx_24x8_l1);
//TBLIS_CONFIG_INSTANTIATE(skx_24x8_l2);
//TBLIS_CONFIG_INSTANTIATE(skx_16x12_l1);
TBLIS_CONFIG_INSTANTIATE(skx_16x12_l2);
//TBLIS_CONFIG_INSTANTIATE(skx_12x16_l1);
//TBLIS_CONFIG_INSTANTIATE(skx_12x16_l2);
//TBLIS_CONFIG_INSTANTIATE(skx_8x24_l1);
//TBLIS_CONFIG_INSTANTIATE(skx_8x24_l2);
//TBLIS_CONFIG_INSTANTIATE(skx_6x32_l1);
//TBLIS_CONFIG_INSTANTIATE(skx_6x32_l2);
//TBLIS_CONFIG_INSTANTIATE(skx_8x8_l1);
//TBLIS_CONFIG_INSTANTIATE(skx_8x8_l2);
//TBLIS_CONFIG_INSTANTIATE(skx_8x8_l1_flip);
//TBLIS_CONFIG_INSTANTIATE(skx_8x8_l2_flip);
//TBLIS_CONFIG_INSTANTIATE(skx_knl);

}
