#ifndef _TBLIS_CONFIGS_REFERENCE_CONFIG_HPP_
#define _TBLIS_CONFIGS_REFERENCE_CONFIG_HPP_

#include "configs/config_builder.hpp"

namespace tblis
{

inline int reference_check() { return 0; }

TBLIS_BEGIN_CONFIG(reference)

TBLIS_CONFIG_ADD_UKR(_,_,_,_)
TBLIS_CONFIG_COPY_UKR(_,_,_,_)
TBLIS_CONFIG_DOT_UKR(_,_,_,_)
TBLIS_CONFIG_REDUCE_UKR(_,_,_,_)
TBLIS_CONFIG_SCALE_UKR(_,_,_,_)
TBLIS_CONFIG_SET_UKR(_,_,_,_)

TBLIS_CONFIG_TRANS_MR(_,_,_,_)
TBLIS_CONFIG_TRANS_NR(_,_,_,_)
TBLIS_CONFIG_TRANS_ADD_UKR(_,_,_,_)
TBLIS_CONFIG_TRANS_COPY_UKR(_,_,_,_)
TBLIS_CONFIG_TRANS_ROW_MAJOR(_,_,_,_)

TBLIS_CONFIG_GEMM_MR(_,_,_,_)
TBLIS_CONFIG_GEMM_NR(_,_,_,_)
TBLIS_CONFIG_GEMM_KR(_,_,_,_)
TBLIS_CONFIG_GEMM_MC(_,_,_,_)
TBLIS_CONFIG_GEMM_NC(_,_,_,_)
TBLIS_CONFIG_GEMM_KC(_,_,_,_)
TBLIS_CONFIG_GEMM_UKR(_,_,_,_)
TBLIS_CONFIG_GEMM_ROW_MAJOR(_,_,_,_)

TBLIS_CONFIG_PACK_NN_MR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_NN_NR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_SN_MR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_SN_NR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_NS_MR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_NS_NR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_SS_MR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_SS_NR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_NB_MR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_NB_NR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_SB_MR_UKR(_,_,_,_)
TBLIS_CONFIG_PACK_SB_NR_UKR(_,_,_,_)

TBLIS_CONFIG_CHECK(reference_check)

TBLIS_END_CONFIG

}

#endif
